### PR TITLE
Reader raw

### PR DESCRIPTION
**Pull request by dblock**
*Issue #, if available:*

#338 

*Description of changes:*

Proposing an implementation to get raw data from a reader. The naming is the hardest part, I wanted `toString`, but that doesn't make sense for a binary reader.  Also will add more tests if we can agree on the name.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dblock** [comment]
Arguments for this PR vs. doing a helper function in `ion`.

A helper function would do, but as other helper functions you would have to check what kind of reader you have (binary vs. text). This leads to code [like this](https://github.com/amzn/ion-js/blob/master/src/Ion.ts#L91).

**Comment by pbcornell** [comment]
Current thoughts:
* as far as i know, ion-java's `IonReader` doesn't provide such a method.  that library has been around for a while;  not sure why ion-js would be special in this regard
* `Writer.writeValues()` seems to provide the desired functionality (and more, I'd say);  the proposal seems to be providing some convenience, but that doesn't suggest to me an addition to `Reader`
* the return value from `raw()` should be effectively the same as the input passed to `makeReader()` (modulo text formatting and perhaps subtle binary encoding differences, or if the use case is to get some subset of what is being read);  any reason not to simply hang on to the original input?

Perhaps I'm not fully understanding this use case, or perhaps it's a less common use case that doesn't suggest an api addition to me.

**Comment by dblock** [comment]
My use case is that I have a large ion document and I am extracting an ion subdocument from it, then sending it to some other service.

**Comment by almann** [comment]
Can you please rebase this PR against `master`, thanks!

**Comment by dblock** [comment]
@almann This got closed? I understand this API as proposed is not what we want. Could you please  comment on how one can achieve my scenario?

**Comment by zslayton** [comment]
@dblock We recently deleted the `development` branch (after merging it into `master`) which caused all open PRs targeting `development` to be closed as a side effect. Sorry about that. I don't seem to have the ability to re-open this PR--the only way to keep it going would be to open another one targeting `master` instead.

**Comment by dblock** [comment]
I reopened this as https://github.com/amzn/ion-js/pull/435.

**Pull request closed without merging**
